.TH "C:/Users/phyrct/Dropbox/Me/Coding/kermit/kermit/kermit.py" 3 "Tue May 24 2016" "kermit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/phyrct/Dropbox/Me/Coding/kermit/kermit/kermit.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBkermit\&.KerrArray\fP"
.br
.ti -1c
.RI "class \fBkermit\&.KerrGUI\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBkermit\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBkermit\&.GRAY_RANGE\fP = (0,65535)"
.br
.ti -1c
.RI "tuple \fBkermit\&.IM_SIZE\fP = (512,672)"
.br
.ti -1c
.RI "tuple \fBkermit\&.AN_IM_SIZE\fP = (554,672)"
.br
.ti -1c
.RI "tuple \fBkermit\&.StringTypes\fP = (str,unicode)"
.br
.ti -1c
.RI "string \fBkermit\&.ex_data1\fP = 'ExampleData1'"
.br
.ti -1c
.RI "string \fBkermit\&.ex_data2\fP = 'ExampleData2'"
.br
.ti -1c
.RI "string \fBkermit\&.tmp_dir\fP = 'tmp'"
.br
.ti -1c
.RI "string \fBkermit\&.example_im_fol\fP = r'C:\\Users\\phyrct\\Dropbox\\Me\\Coding\\kermit'"
.br
.ti -1c
.RI "\fBkermit\&.bkim\fP = io\&.imread('bknd\&.png')"
.br
.ti -1c
.RI "\fBkermit\&.unpim\fP = io\&.imread('unpro\&.png')"
.br
.ti -1c
.RI "\fBkermit\&.im\fP = io\&.imread('sub\&.png')"
.br
.ti -1c
.RI "list \fBkermit\&.proc_list\fP = [im]"
.br
.ti -1c
.RI "\fBkermit\&.v1\fP = CollectionViewer(proc_list)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for kermit from the source code\&.
