.TH "kermit" 3 "Tue May 24 2016" "kermit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kermit \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBKerrArray\fP"
.br
.ti -1c
.RI "class \fBKerrGUI\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBGRAY_RANGE\fP = (0,65535)"
.br
.ti -1c
.RI "tuple \fBIM_SIZE\fP = (512,672)"
.br
.ti -1c
.RI "tuple \fBAN_IM_SIZE\fP = (554,672)"
.br
.ti -1c
.RI "tuple \fBStringTypes\fP = (str,unicode)"
.br
.ti -1c
.RI "string \fBex_data1\fP = 'ExampleData1'"
.br
.ti -1c
.RI "string \fBex_data2\fP = 'ExampleData2'"
.br
.ti -1c
.RI "string \fBtmp_dir\fP = 'tmp'"
.br
.ti -1c
.RI "string \fBexample_im_fol\fP = r'C:\\Users\\phyrct\\Dropbox\\Me\\Coding\\kermit'"
.br
.ti -1c
.RI "\fBbkim\fP = io\&.imread('bknd\&.png')"
.br
.ti -1c
.RI "\fBunpim\fP = io\&.imread('unpro\&.png')"
.br
.ti -1c
.RI "\fBim\fP = io\&.imread('sub\&.png')"
.br
.ti -1c
.RI "list \fBproc_list\fP = [\fBim\fP]"
.br
.ti -1c
.RI "\fBv1\fP = CollectionViewer(\fBproc_list\fP)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple kermit\&.AN_IM_SIZE = (554,672)"

.SS "kermit\&.bkim = io\&.imread('bknd\&.png')"

.SS "string kermit\&.ex_data1 = 'ExampleData1'"

.SS "string kermit\&.ex_data2 = 'ExampleData2'"

.SS "string kermit\&.example_im_fol = r'C:\\Users\\phyrct\\Dropbox\\Me\\Coding\\kermit'"

.SS "tuple kermit\&.GRAY_RANGE = (0,65535)"

.SS "kermit\&.im = io\&.imread('sub\&.png')"

.SS "tuple kermit\&.IM_SIZE = (512,672)"

.SS "list kermit\&.proc_list = [\fBim\fP]"

.SS "tuple kermit\&.StringTypes = (str,unicode)"

.SS "string kermit\&.tmp_dir = 'tmp'"

.SS "kermit\&.unpim = io\&.imread('unpro\&.png')"

.SS "kermit\&.v1 = CollectionViewer(\fBproc_list\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for kermit from the source code\&.
