.TH "kerrlist" 3 "Tue May 24 2016" "kermit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kerrlist \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBKerrList\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBGRAY_RANGE\fP = (0,65535)"
.br
.ti -1c
.RI "tuple \fBIM_SIZE\fP = (512,672)"
.br
.ti -1c
.RI "tuple \fBAN_IM_SIZE\fP = (554,672)"
.br
.ti -1c
.RI "tuple \fBStringTypes\fP = (str,unicode)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple kerrlist\&.AN_IM_SIZE = (554,672)"

.SS "tuple kerrlist\&.GRAY_RANGE = (0,65535)"

.SS "tuple kerrlist\&.IM_SIZE = (512,672)"

.SS "tuple kerrlist\&.StringTypes = (str,unicode)"

.SH "Author"
.PP 
Generated automatically by Doxygen for kermit from the source code\&.
