.TH "C:/Users/phyrct/Dropbox/Me/Coding/kermit/kermit/kerrlist.py" 3 "Tue May 24 2016" "kermit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/phyrct/Dropbox/Me/Coding/kermit/kermit/kerrlist.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBkerrlist\&.KerrList\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBkerrlist\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBkerrlist\&.GRAY_RANGE\fP = (0,65535)"
.br
.ti -1c
.RI "tuple \fBkerrlist\&.IM_SIZE\fP = (512,672)"
.br
.ti -1c
.RI "tuple \fBkerrlist\&.AN_IM_SIZE\fP = (554,672)"
.br
.ti -1c
.RI "tuple \fBkerrlist\&.StringTypes\fP = (str,unicode)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for kermit from the source code\&.
